[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Surfaces"
authors = [{name = "Natalia F B Teruel", email = "natalia.fagundes.borges.teruel@umontreal.ca"}]
dynamic = ["version", "description"]
